// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "6babec06-70a2-4f4d-9b5d-29c931928453");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1600877692);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1600877812);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1600876874);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1600877114);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1600876994);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1600877572);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1600792041);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1600791921);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 798720);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1600706023);
user_pref("browser.laterrun.bookkeeping.sessionCount", 7);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.impressionId", "{229f2328-286a-43e1-98a1-e17565f68c26}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1600794000);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 1);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1600876925913");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1600878712913");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1600876864553");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1600880464553");
user_pref("browser.search.region", "VN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190215002044");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1600850850");
user_pref("browser.slowStartup.averageTime", 3597);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20190215002044");
user_pref("browser.startup.homepage_override.mstone", "65.0.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1600706035684");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "65.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "b948654463394603b5564300874e6ac6");
user_pref("extensions.blocklist.lastModified", "Tue, 22 Sep 2020 11:07:55 GMT");
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1600877692);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190215002044");
user_pref("extensions.lastAppVersion", "65.0.1");
user_pref("extensions.lastPlatformVersion", "65.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"28cbd3ef-c3db-448e-989d-76b55a1c69a6\",\"screenshots@mozilla.org\":\"02c30fab-2f77-4dfc-ae3a-e41b9fede456\",\"webcompat-reporter@mozilla.org\":\"c1eac1e9-dcca-4a4d-aace-26ecd63f7bde\",\"webcompat@mozilla.org\":\"17685b8c-bd0d-4a9d-b7ca-8c9fcdcb3cea\",\"baidu-code-update@mozillaonline.com\":\"5dd8efec-1e90-424e-a893-904ffed91b83\",\"fxmonitor@mozilla.org\":\"9a2814ae-99b7-4f62-a862-9cf69523fa03\"}");
user_pref("idle.lastDailyNotification", 1600793669);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1600706067);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190215002044");
user_pref("media.gmp-manager.lastCheck", 1600841498);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1600793669);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "2ebca310-0d0b-416c-9470-68d593559036");
user_pref("security.sandbox.plugin.tempDirSuffix", "84232fab-e888-48ea-bba7-c14dc2a5ab6b");
user_pref("services.blocklist.addons.checked", 1600877571);
user_pref("services.blocklist.gfx.checked", 1600877571);
user_pref("services.blocklist.onecrl.checked", 1600877571);
user_pref("services.blocklist.pinning.checked", 1600877571);
user_pref("services.blocklist.plugins.checked", 1600877571);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1600861560124\"");
user_pref("services.settings.last_update_seconds", 1600877571);
user_pref("services.settings.main.language-dictionaries.last_check", 1600877571);
user_pref("services.settings.main.sites-classification.last_check", 1600877571);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1600793669);
user_pref("toolkit.startup.last_success", 1600850845);
user_pref("toolkit.telemetry.cachedClientID", "a07dc2ec-d7b3-4348-8e89-3e318af6de06");
user_pref("toolkit.telemetry.previousBuildID", "20190215002044");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
